# Generated by Django 4.2.7 on 2023-11-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('uer_name', models.CharField(max_length=100)),
                ('user_mobile_number', models.IntegerField(max_length=13)),
                ('user_address', models.CharField(max_length=250)),
                ('user_parmanent_address', models.CharField(max_length=250)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_master',
            },
        ),
    ]
